# -*- coding: utf-8 -*-
"""pandasTask.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16j54voGXl-SRlEvquHs9SK77TPcsnwKZ
"""

import pandas as pd
import numpy as np

"""Reading the csv 

"""

df=pd.read_csv("/content/purchase_data.csv")

df=df.sort_values(by='Age')

df

df['Age'].max()

df['Age'].min()

list1=np.arange(6,50,4).tolist()

print(list1)

df['bins'] = pd.cut(x=df['Age'], bins=list1)
print(df)

counts=df.value_counts('bins')  #Purchase count for Each group
print(counts)

df['bins'].value_counts()

fstbin = df['bins']==pd.Interval(left=6,right=10)

df[fstbin]

avg1st=df[fstbin]['Price'].mean()
print(avg1st)                   # mean ,Purchase Count and sum for 1st group (6,10] 
sum1st=df[fstbin]['Price'].sum()
count1=df[fstbin]["Purchase ID"].count()
print(count1)
print(sum1st)

bin2= df['bins']==pd.Interval(left=10,right=14)

df[bin2]

mean2=df[bin2]['Price'].mean() 
print(mean2)                       # mean , sum and Purchase count  for 2nd group (10,14] 
sum2=df[bin2]['Price'].sum()
print(sum1st)
count2=df[bin2]["Purchase ID"].count()
print(count2)

bin3= df['bins']==pd.Interval(left=14,right=18)
                                                 # mean ,sum ,purchase count for 3rd group (14,18] 
print(df[bin3]['Price'].mean())
sum3=df[bin3]['Price'].sum()
print(sum1st)
count3=df[bin3]["Purchase ID"].count()
print(count3)

bin4= df['bins']==pd.Interval(left=18,right=22)
                                                 # mean,sum and purchase  for 4th group (18,22] 
print(df[bin4]['Price'].mean())
sum4=df[bin4]['Price'].sum()
print(sum4)
count4=df[bin4]["Purchase ID"].count()
print(count4)

bin5= df['bins']==pd.Interval(left=22,right=26)
                                                 # mean,sum and Purchase count  for 5rd group (22,26] 
print(df[bin5]['Price'].mean())
sum5=df[bin5]['Price'].sum()
print(sum5)

count5=df[bin5]["Purchase ID"].count()
print(count5)



df

df['Purchase ID'].count() # purchase count

df['Price'].mean() # average price

df['Price'].sum() # Total Purchase price

"""Top five spenders"""

new=df.nlargest(5,["Price"]) #top five spenders

new[['SN',"Price"]]

new["Price"].mean()  # average purchase value of top 5 spenders

new['Price'].sum() #total Purchase value of top 5 spenders

filt=df['Item Name'].value_counts().nlargest(5)
print(filt)

filt.index



filt=df['Item Name'].isin(filt.index)

df[filt]['Price'].sum()  # purchase value for popular 5

df[filt]['Item ID'].unique() # Item ID of top Most

#purchase count
df[filt]["Purchase ID"].count()

