# -*- coding: utf-8 -*-
"""pdftotext.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S9LfdEikPNs9kdvd2qAWPzvJ2DaWB43r
"""



import PyPDF2

pdfFileObj = open('sample.pdf', 'rb')

print(pdfFileObj)

pdfReader = PyPDF2.PdfFileReader(pdfFileObj)

n=pdfReader.numPages

print(n)

textfile= open('textfile.txt','w')

for i in range(n):
  
  content=pdfReader.getPage(i).extractText()
  print(content)
  textfile.write(content)
  textfile.write('\n')

file=open('textfile.txt','r')

data = file.read()

def seaching_Word(sw):
  if sw in data:
    occurrences = data.count(sw)
    return occurrences
  else:
    return "Not found matched word"

sw=input("Enter the word to search")
print(seaching_Word(sw))
